### ISSUE TITLE
Double Acutes 

### ISSUE THREAD

**Issue by brclar15** [homermultitext/hmt-mom#109]
We had changed to allowing double graves to pass in MOM by using the combining double grave character. 
Now, it seems that we need to add double acutes to list of passable characters. See urn:cts:greekLit:tlg0012.tlg001.msA:18.309

urn:cite:hmt:vaimg.VA245RN-0416@0.2,0.3276,0.444,0.0308

**Comment by neelsmith** [comment]
moved to hmt-utils
