### ISSUE TITLE
Discrepancies between reported number of failed lexical tokens and actual observed failures

### ISSUE THREAD

**Issue by cjschu17** [homermultitext/hmt-mom#115]
When running validation on 239r, the validation summary said that there were 14 tokens which failed to parse. However, when examining the details there are only 4 lexical tokens with an "X" next to them. This seems to be restricted to this folio as folio 239v reported 9 lexical token failures and that number of failures appeared in the details. If further folios also show this discrepancy we will report them here:

239r: 14 failures reported, 4 observed

**Comment by brclar15** [comment]
240r: 9 failures reported, 5 observed

**Comment by neelsmith** [comment]
fixed
