### ISSUE TITLE
Failing to parse words before punctuation

### ISSUE THREAD

**Issue by brclar15** [homermultitext/hmt-mom#116]
MOM is repeatedly skipping over words that are followed by a high stop. When a space is added in between the two, and the page is revalidated, the word then does parse correctly.

Example: urn:cite:hmt:msA.240r
the μήτηρ at the end of urn:cts:greekLit:tlg0012.tlg001.msA:18.70 does not show up in the index in the build folder of MOM if the high stop is directly after it, but it does appear if there is a space between the two.
The same thing happens with the προσηύδᾱ in urn:cts:greekLit:tlg0012.tlg001.msA:18.72

**Comment by neelsmith** [comment]
fixed
