### ISSUE TITLE
Issue with Error Counting

### ISSUE THREAD

**Issue by mwauke** [homermultitext/hmt-mom#117]
On 250r, MOM reports there being 8 errors in the lexical tokens (389/8/397). However, only two errors appear in the index. The two that appear are 
urn:cts:greekLit:tlg0012.tlg001.msA:18.566@νείσοντο[1] (already submitted in utils)
urn:cts:greekLit:tlg5026.msA.hmt:18.205@δονακῆεν[1] (already submitted in utils)

**Comment by neelsmith** [comment]
fixed
