### ISSUE TITLE
Miscounted Errors in Validation of Lexical Tokens: urn:cite:hmt:msA.242r

### ISSUE THREAD

**Issue by cshanley18** [homermultitext/hmt-mom#118]
MOM is consistently listing a different number of lexical token errors in the summary compared with the errors which actually show up in the details of the validation report.  On 242r, for instance, the summary says that 9 words out of 439 fail to pass validation.  However, the details of the report only list 6 lexical tokens as failing validation.

**Comment by neelsmith** [comment]
fixed
