### ISSUE TITLE
Add to acceptable characters: ☉

### ISSUE THREAD

**Issue by StephanieML** [homermultitext/hmt-mom#159]
for a scholion that used the helios symbol for the word ἡλιου, we had proposed using this character: ☉

it is currently rejected by mom 

SCHOLION ID: urn:cts:greekLit:tlg5026.msA.hmt:8.2
FOLIO: urn:cite2:hmt:msA.v1:100v
IMAGE: urn:cite2:hmt:vaimg.2017a:VA100VN-0603@0.2892,0.4533,0.01971,0.01480

urn:cite2:hmt:vaimg.2017a:VA100VN-0603@0.194,0.3883,0.229,0.1115#

**Comment by StephanieML** [comment]
in the xml we have treated is as an abbreviation, so we had marked it up as follows:

`<choice><abbr>☉</abbr><expan>ἡλιου</expan></choice>`

**Comment by StephanieML** [comment]
symbol used again here:

PASSAGE: urn:cts:greekLit:tlg5026.msA.hmt:8.17
IMAGE: urn:cite2:hmt:vaimg.2017a:VA101RN_0273@0.6531,0.3411,0.01971,0.01480
SURFACE: urn:cite2:hmt:msA.v1:101r

this time for τον ἡλιον

**Comment by StephanieML** [comment]
and again:

PASSAGE: urn:cts:greekLit:tlg5026.msA.hmt:8.65.
IMAGE: urn:cite2:hmt:vaimg.2017a:VA102RN_0274@0.5280,0.1433,0.02303,0.01853
SURFACE: urn:cite2:hmt:msA.v1:102r

**Comment by neelsmith** [comment]
Transferred to `hmt-textmodel` repository.  Closing here.
