### ISSUE TITLE
DSE validation on bifolio spreads

### ISSUE THREAD

**Issue by StephanieML** [homermultitext/hmt-mom#165]
Once you have dse for a full bifolio spread, there is an error in counting indexed images, because it's counting based on everything indexed to the image, not the surface. So it will tell you you have inconsistencies in your data. 

e.g. "Error in indexing: 69 text passages indexed to image vb_103v_104r, but 37 passages indexed to page 103v"

**Comment by neelsmith** [comment]
done.
