### ISSUE TITLE
Add to acceptable characters: ☾

### ISSUE THREAD

**Issue by StephanieML** [homermultitext/hmt-mom#166]
Moon symbol is used for σεληνην

Image: http://www.homermultitext.org/ict2/?urn=urn:cite2:hmt:vaimg.2017a:VA111RN_0283@0.1709,0.7237,0.6293,0.0497

Text: urn:cts:greekLit:tlg5026.msA.dipl:8.345

**Comment by neelsmith** [comment]
Transferred to `hmt-textmodel` repository.  Closing here.
