### ISSUE TITLE
Sigma Tokenization Error Example: urn:cite:hmt:msA.157r: ὑψόσ'

### ISSUE THREAD

**Issue by StephanieML** [homermultitext/hmt-mom#29]
passage: urn:cts:greekLit:tlg0012.tlg001.msA:12.138
form: ὑψόσ'

ὑψόσ' passes morpheus but not MOM

**Comment by neelsmith** [comment]
Fixed?  Test before closing.

**Comment by neelsmith** [comment]
Tested.
