### ISSUE TITLE
Tokenization Error urn:cite:hmt:msA.155r: ἐμάχεντο

### ISSUE THREAD

**Issue by StephanieML** [homermultitext/hmt-mom#33]
urn:cts:greekLit:tlg5026.msA.hmt:12.B7

ἐμάχεντο has the ν marked in 'del' and is trying to parse it as one whole word, not splicing out the content in 'del'. We want the tokenizer to skip over content marked in 'del'.

**Comment by neelsmith** [comment]
Transferring to hmt-utils project
