### ISSUE TITLE
Proposed adjustment to validating Pers/Place Names

### ISSUE THREAD

**Issue by brclar15** [homermultitext/hmt-mom#58]
When we run validation, mom only seems to find errors at the end of pers/place name URNS
for example, it will catch: urn:cite:hmt:pers.pers.86, or palace.palace5
but. it did not catch: urn:cote:hmt:pers.pers86

Is there a way to check the entire URN for type-o's?

**Comment by neelsmith** [comment]
should be valid now by parsing URNs.  Verify before closing

**Comment by neelsmith** [comment]
tested.
