### ISSUE TITLE
Lack of Notification on Multiples of the Same Error in the Same Passage

### ISSUE THREAD

**Issue by StephanieML** [homermultitext/hmt-mom#66]
We noticed today if the exact same error appears in the same passage, hmt-mom will only indicate that there is one error. If they're in different passages it will tell you there are two but it will not tell you there are two in the same passage.

For example, today on urn:cite:hmt:msA.151v there are two occurrences of ίσου in urn:cts:greekLit:tlg5026.msA.hmt:11.263, but we only see it showing up in lextokens once for that passage.

**Comment by neelsmith** [comment]
Should be cleared up in current use of explicit subindexes on all subreff
