### ISSUE TITLE
Possible source of Verification Freezing

### ISSUE THREAD

**Issue by brclar15** [homermultitext/hmt-mom#99]
If MOM runs into an unaccepted character, such as the "+" sign, it will freeze. This happened on 9v with the authorities list when the "+" sign was in the xml document.

Current Solution - the punctuation that resembles a "+" in the manuscript gets marked up as a ‡, or if the sign trails a bit at the end, as a ⁑

**Comment by neelsmith** [comment]
Should be cleared up by new dependencies on greeklang.
